lesson3+lesson4
AlesyaStupeneva/TeachMeSkills pull request #5
Opened 2021-11-01 19:49 UTC by AlesyaStupeneva

new material

2021-11-02 08:00 UTC, atarantey commented on lesson 1/index.html
> +                    <img class="main-logo" src="../lesson 4/logotype.png" alt="logotype"/>
пробелы в пути к картинках очень не желательны

2021-11-02 08:03 UTC, atarantey requested changes

2021-11-02 08:03 UTC, atarantey commented on lesson 1/index.html
> +                        <legend>Try Your <font color="red"> FREE</font> Trial Today</legend>                                <input type="text" required placeholder="Name"></br>
тэг font лучше вообще не использовать, вместо него можно <span> и нужный css стиль

2021-11-02 08:03 UTC, atarantey commented on lesson 1/index.html
> +                        <a href="https://www.facebook.com"><img src="../lesson 3/img/logo-f.png"></a>
тоже самое с пробелами, что и в первом комментрии

2021-11-03 19:37 UTC, AlesyaStupeneva commented on lesson 1/index.html
> +                        <legend>Try Your <font color="red"> FREE</font> Trial Today</legend>                                <input type="text" required placeholder="Name"></br>
Заменила на 
<legend>Try Your <span> FREE</span> Trial Today</legend>
в CSS
.forma span {
    text-transform: uppercase;
    color: red;
}

2021-11-08 20:31 UTC, atarantey approved these changes

2021-11-09 02:50 UTC, merged